// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTuvoRbR6JRs6TPtXX2jYFJtdUCWNfncw',
    appId: '1:342147376446:web:8bad98d235c19cacae386f',
    messagingSenderId: '342147376446',
    projectId: 'anuvad-7cf86',
    authDomain: 'anuvad-7cf86.firebaseapp.com',
    storageBucket: 'anuvad-7cf86.appspot.com',
    measurementId: 'G-SKT27G8ZZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7etXX-7QNEhNuEe1pQa8ixDI33KIrgAY',
    appId: '1:342147376446:android:e3c8b75ce93d5f6fae386f',
    messagingSenderId: '342147376446',
    projectId: 'anuvad-7cf86',
    storageBucket: 'anuvad-7cf86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr8UIibcLIJyRZho6KodAJuvr5vDIu3a4',
    appId: '1:342147376446:ios:0cba61ccdcc666d2ae386f',
    messagingSenderId: '342147376446',
    projectId: 'anuvad-7cf86',
    storageBucket: 'anuvad-7cf86.appspot.com',
    iosClientId: '342147376446-o8sligjhdmqc6p22cn7to9geb4jeg1uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.anuvadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr8UIibcLIJyRZho6KodAJuvr5vDIu3a4',
    appId: '1:342147376446:ios:0cba61ccdcc666d2ae386f',
    messagingSenderId: '342147376446',
    projectId: 'anuvad-7cf86',
    storageBucket: 'anuvad-7cf86.appspot.com',
    iosClientId: '342147376446-o8sligjhdmqc6p22cn7to9geb4jeg1uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.anuvadApp',
  );
}
